package com.github.kraudy.compiler;

import java.util.List;
import java.util.Map;

import com.github.kraudy.compiler.CompilationPattern.CompCmd;
import com.github.kraudy.compiler.CompilationPattern.ParamCmd;
import com.github.kraudy.compiler.CompilationPattern.SysCmd;
import com.github.kraudy.compiler.CompilationPattern.ValCmd;

/**
 * Dry compile plan as a paste-ready CL command list (stream file, not a CL PGM).
 * Same order as {@link MasterCompiler#buildTargets}: global before, per-target
 * before / migrate / CRT* / success / after, global after.
 */
public final class CompileScriptWriter {

  private CompileScriptWriter() {}

  public static String toCl(BuildSpec spec) {
    StringBuilder sb = new StringBuilder();
    sb.append("/* Generated by MasterCompiler — run on IBM i after CHGCURLIB if needed */\n");

    if (spec == null) return sb.toString();

    writeHooks(sb, spec.before);

    for (Map.Entry<TargetKey, BuildSpec.TargetSpec> entry : spec.targets.entrySet()) {
      TargetKey key = entry.getKey();
      BuildSpec.TargetSpec targetSpec = entry.getValue();
      if (key == null || targetSpec == null) continue;

      writeHooks(sb, targetSpec.before);

      String crt = CommandStringParser.toPasteableCommand(
          key, spec.defaults, targetSpec.params);
      if (needsMemberCopy(key, targetSpec) && streamPath(key, targetSpec) != null) {
        writeLine(sb, copyFromStmf(key, streamPath(key, targetSpec)));
      }
      if (crt != null && !crt.isEmpty()) {
        writeLine(sb, crt);
      }

      writeHooks(sb, targetSpec.success);
      writeHooks(sb, targetSpec.after);
    }

    writeHooks(sb, spec.after);
    return sb.toString();
  }

  static boolean needsMemberCopy(TargetKey key, BuildSpec.TargetSpec targetSpec) {
    if (streamPath(key, targetSpec) == null) return false;
    CompCmd cmd = key.getCompilationCommand();
    if (cmd == null) return false;
    return !CompilationPattern.getCommandPattern(cmd).contains(ParamCmd.SRCSTMF);
  }

  private static String streamPath(TargetKey key, BuildSpec.TargetSpec targetSpec) {
    if (targetSpec != null && targetSpec.params != null) {
      String fromParams = targetSpec.params.get(ParamCmd.SRCSTMF);
      if (fromParams != null && !fromParams.trim().isEmpty()) {
        return CommandStringParser.stripClQuotes(fromParams);
      }
    }
    if (key != null && key.containsStreamFile()) {
      String stmf = key.getStreamFile();
      if (stmf != null && !stmf.trim().isEmpty()) {
        return CommandStringParser.stripClQuotes(stmf);
      }
    }
    return null;
  }

  private static String copyFromStmf(TargetKey key, String fromStmf) {
    CommandObject cmd = new CommandObject(SysCmd.CPYFRMSTMF)
        .put(ParamCmd.FROMSTMF, fromStmf)
        .put(ParamCmd.TOMBR, key.getMemberPath())
        .put(ParamCmd.MBROPT, ValCmd.REPLACE)
        .put(ParamCmd.CVTDTA, "*AUTO")
        .put(ParamCmd.STMFCODPAG, MasterCompiler.UTF8_CCSID);
    return CommandStringParser.toPasteable(cmd.getCommandStringWithoutSummary());
  }

  private static void writeHooks(StringBuilder sb, List<CommandObject> hooks) {
    if (hooks == null) return;
    for (CommandObject hook : hooks) {
      if (hook == null) continue;
      String line = CommandStringParser.toPasteable(hook.getCommandStringWithoutSummary());
      if (line != null && !line.trim().isEmpty()) {
        writeLine(sb, line);
      }
    }
  }

  private static void writeLine(StringBuilder sb, String line) {
    if (sb.length() > 0 && sb.charAt(sb.length() - 1) != '\n') {
      sb.append('\n');
    }
    sb.append(line).append('\n');
  }
}
