package com.github.kraudy.compiler;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import com.github.kraudy.compiler.CompilationPattern.ParamCmd;

/**
 * Writes a readable YAML build spec from a {@link BuildSpec}.
 * Emits global hooks, per-target hooks, and {@code params}
 * (SRCSTMF, MODULE, PGM, ...). Target map order is preserved (topo-sorted).
 */
public final class SpecWriter {

  private SpecWriter() {}

  public static String toYaml(BuildSpec spec) {
    return toYaml(spec, null);
  }

  public static String toYaml(BuildSpec spec, String scanRootComment) {
    StringBuilder sb = new StringBuilder();
    sb.append("# Generated by MasterCompiler --scan\n");
    if (scanRootComment != null && !scanRootComment.isEmpty()) {
      sb.append("# Root: ").append(scanRootComment).append("\n");
    }
    if (spec.getBaseDirectory() != null) {
      sb.append("# Base directory: ").append(spec.getBaseDirectory()).append("\n");
    }
    sb.append("\n");

    writeHookSection(sb, "before", spec.before, "");
    writeHookSection(sb, "after", spec.after, "");
    writeHookSection(sb, "success", spec.success, "");
    writeHookSection(sb, "failure", spec.failure, "");

    sb.append("targets:\n");

    for (Map.Entry<TargetKey, BuildSpec.TargetSpec> entry : spec.targets.entrySet()) {
      TargetKey key = entry.getKey();
      BuildSpec.TargetSpec targetSpec = entry.getValue();

      sb.append("  \"").append(escapeYamlDouble(key.asString())).append("\":\n");

      boolean hasParams = targetSpec.params != null && !targetSpec.params.isEmpty();
      boolean hasBefore = targetSpec.before != null && !targetSpec.before.isEmpty();
      boolean hasAfter = targetSpec.after != null && !targetSpec.after.isEmpty();
      boolean hasSuccess = targetSpec.success != null && !targetSpec.success.isEmpty();
      boolean hasFailure = targetSpec.failure != null && !targetSpec.failure.isEmpty();

      if (!hasParams && !hasBefore && !hasAfter && !hasSuccess && !hasFailure) {
        sb.append("    params: {}\n");
        sb.append("\n");
        continue;
      }

      writeHookSection(sb, "before", targetSpec.before, "    ");
      writeHookSection(sb, "after", targetSpec.after, "    ");
      writeHookSection(sb, "success", targetSpec.success, "    ");
      writeHookSection(sb, "failure", targetSpec.failure, "    ");

      if (hasParams) {
        sb.append("    params:\n");
        List<ParamCmd> ordered = orderedParams(targetSpec.params);
        for (ParamCmd param : ordered) {
          String value = targetSpec.params.get(param);
          if (value == null) continue;
          writeParam(sb, param, value);
        }
      } else {
        sb.append("    params: {}\n");
      }
      sb.append("\n");
    }

    return sb.toString();
  }

  /**
   * Emit hooks as a YAML list (supports repeated commands like multiple ADDMSGD).
   * Indent is the YAML indent for the section key ("" global, "    " under target).
   */
  private static void writeHookSection(
      StringBuilder sb, String section, List<CommandObject> hooks, String indent) {
    if (hooks == null || hooks.isEmpty()) return;

    sb.append(indent).append(section).append(":\n");
    String itemIndent = indent + "  ";
    String cmdIndent = indent + "    ";
    String paramIndent = indent + "      ";

    for (CommandObject cmd : hooks) {
      if (cmd == null) continue;
      sb.append(itemIndent).append("- ").append(cmd.getSystemCommandName()).append(":\n");
      List<ParamCmd> pattern = CompilationPattern.getCommandPattern(cmd.getSystemCommand());
      boolean wroteAny = false;
      for (ParamCmd param : pattern) {
        if (!cmd.containsKey(param)) continue;
        String value = stripIbmQuotes(cmd.get(param));
        if (value == null || value.isEmpty()) continue;

        if ((param == ParamCmd.OBJ || param == ParamCmd.MODULE) && value.contains(" ")) {
          sb.append(paramIndent).append(param.name()).append(":\n");
          for (String part : value.trim().split("\\s+")) {
            if (part.isEmpty()) continue;
            String name = part.replaceAll("^.*[\\\\/]", "");
            sb.append(paramIndent).append("  - ").append(name).append("\n");
          }
          wroteAny = true;
          continue;
        }

        sb.append(paramIndent).append(param.name()).append(": ");
        if (needsQuoting(value)) {
          sb.append("\"").append(escapeYamlDouble(value)).append("\"");
        } else {
          sb.append(value);
        }
        sb.append("\n");
        wroteAny = true;
      }
      if (!wroteAny) {
        sb.append(paramIndent).append("{}\n");
      }
    }
    if (indent.isEmpty()) {
      sb.append("\n");
    }
  }

  public static void writeToFile(BuildSpec spec, String outputPath) throws IOException {
    writeToFile(spec, outputPath, null);
  }

  public static void writeToFile(BuildSpec spec, String outputPath, String scanRootComment)
      throws IOException {
    Path path = Paths.get(outputPath);
    Path parent = path.getParent();
    if (parent != null) {
      Files.createDirectories(parent);
    }
    Files.write(path, toYaml(spec, scanRootComment).getBytes(StandardCharsets.UTF_8));
  }

  private static List<ParamCmd> orderedParams(Map<ParamCmd, String> params) {
    List<ParamCmd> ordered = new ArrayList<>();
    if (params.containsKey(ParamCmd.SRCSTMF)) ordered.add(ParamCmd.SRCSTMF);
    if (params.containsKey(ParamCmd.MODULE)) ordered.add(ParamCmd.MODULE);
    if (params.containsKey(ParamCmd.PGM)) ordered.add(ParamCmd.PGM);
    for (ParamCmd p : params.keySet()) {
      if (p == ParamCmd.SRCSTMF || p == ParamCmd.MODULE || p == ParamCmd.PGM) continue;
      ordered.add(p);
    }
    return ordered;
  }

  private static void writeParam(StringBuilder sb, ParamCmd param, String value) {
    value = stripIbmQuotes(value);
    if (param == ParamCmd.MODULE) {
      String[] modules = value.trim().split("\\s+");
      if (modules.length > 1 || (modules.length == 1 && !modules[0].isEmpty())) {
        sb.append("      ").append(param.name()).append(":\n");
        for (String mod : modules) {
          if (mod.isEmpty()) continue;
          String name = mod.replaceAll("^.*[\\\\/]", "");
          sb.append("        - ").append(name).append("\n");
        }
        return;
      }
    }

    sb.append("      ").append(param.name()).append(": ");
    if (needsQuoting(value)) {
      sb.append("\"").append(escapeYamlDouble(value)).append("\"");
    } else {
      sb.append(value);
    }
    sb.append("\n");
  }

  /** Peel validateParamValue IBM i quotes so YAML stays logical (re-applied on load). */
  private static String stripIbmQuotes(String value) {
    if (value == null) return null;
    String s = value.trim();
    while (s.startsWith("''") && s.endsWith("''") && s.length() >= 4) {
      s = s.substring(2, s.length() - 2).trim();
    }
    return s;
  }

  private static boolean needsQuoting(String value) {
    if (value.isEmpty()) return true;
    if (value.indexOf(':') >= 0 || value.indexOf('#') >= 0 || value.indexOf('\'') >= 0) return true;
    if (value.indexOf('"') >= 0 || value.indexOf(' ') >= 0) return true;
    if (value.indexOf('*') >= 0 || value.indexOf('/') >= 0) return true;
    return false;
  }

  private static String escapeYamlDouble(String s) {
    return s.replace("\\", "\\\\").replace("\"", "\\\"");
  }
}
