package com.github.kraudy.compiler;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import com.github.kraudy.compiler.CompilationPattern.ParamCmd;

/**
 * Writes a minimal, readable YAML build spec from a {@link BuildSpec}.
 * Only emits {@code targets} with {@code params} (SRCSTMF, MODULE, ...).
 * Target map order is preserved (expected to be topo-sorted).
 */
public final class SpecWriter {

  private SpecWriter() {}

  public static String toYaml(BuildSpec spec) {
    return toYaml(spec, null);
  }

  public static String toYaml(BuildSpec spec, String scanRootComment) {
    StringBuilder sb = new StringBuilder();
    sb.append("# Generated by MasterCompiler --scan\n");
    if (scanRootComment != null && !scanRootComment.isEmpty()) {
      sb.append("# Root: ").append(scanRootComment).append("\n");
    }
    if (spec.getBaseDirectory() != null) {
      sb.append("# Base directory: ").append(spec.getBaseDirectory()).append("\n");
    }
    sb.append("\n");
    sb.append("targets:\n");

    for (Map.Entry<TargetKey, BuildSpec.TargetSpec> entry : spec.targets.entrySet()) {
      TargetKey key = entry.getKey();
      BuildSpec.TargetSpec targetSpec = entry.getValue();

      // Always quote target keys for safe YAML
      sb.append("  \"").append(escapeYamlDouble(key.asString())).append("\":\n");

      if (targetSpec.params == null || targetSpec.params.isEmpty()) {
        sb.append("    params: {}\n");
        sb.append("\n");
        continue;
      }

      sb.append("    params:\n");

      // Prefer stable param order: SRCSTMF first, then MODULE, then rest
      List<ParamCmd> ordered = orderedParams(targetSpec.params);
      for (ParamCmd param : ordered) {
        String value = targetSpec.params.get(param);
        if (value == null) continue;
        writeParam(sb, param, value);
      }
      sb.append("\n");
    }

    return sb.toString();
  }

  public static void writeToFile(BuildSpec spec, String outputPath) throws IOException {
    writeToFile(spec, outputPath, null);
  }

  public static void writeToFile(BuildSpec spec, String outputPath, String scanRootComment)
      throws IOException {
    Path path = Paths.get(outputPath);
    Path parent = path.getParent();
    if (parent != null) {
      Files.createDirectories(parent);
    }
    Files.write(path, toYaml(spec, scanRootComment).getBytes(StandardCharsets.UTF_8));
  }

  private static List<ParamCmd> orderedParams(Map<ParamCmd, String> params) {
    List<ParamCmd> ordered = new ArrayList<>();
    if (params.containsKey(ParamCmd.SRCSTMF)) ordered.add(ParamCmd.SRCSTMF);
    if (params.containsKey(ParamCmd.MODULE)) ordered.add(ParamCmd.MODULE);
    for (ParamCmd p : params.keySet()) {
      if (p == ParamCmd.SRCSTMF || p == ParamCmd.MODULE) continue;
      ordered.add(p);
    }
    return ordered;
  }

  private static void writeParam(StringBuilder sb, ParamCmd param, String value) {
    // MODULE may be space-separated list → YAML list
    if (param == ParamCmd.MODULE) {
      String[] modules = value.trim().split("\\s+");
      if (modules.length > 1 || (modules.length == 1 && !modules[0].isEmpty())) {
        sb.append("      ").append(param.name()).append(":\n");
        for (String mod : modules) {
          if (mod.isEmpty()) continue;
          // Strip *LIBL/ qualification for readable YAML
          String name = mod.replaceAll("^.*[\\\\/]", "");
          sb.append("        - ").append(name).append("\n");
        }
        return;
      }
    }

    sb.append("      ").append(param.name()).append(": ");
    if (needsQuoting(value)) {
      sb.append("\"").append(escapeYamlDouble(value)).append("\"");
    } else {
      sb.append(value);
    }
    sb.append("\n");
  }

  private static boolean needsQuoting(String value) {
    if (value.isEmpty()) return true;
    if (value.indexOf(':') >= 0 || value.indexOf('#') >= 0 || value.indexOf('\'') >= 0) return true;
    if (value.indexOf('"') >= 0 || value.indexOf(' ') >= 0) return true;
    if (value.indexOf('*') >= 0 || value.indexOf('/') >= 0) return true;
    return false;
  }

  private static String escapeYamlDouble(String s) {
    return s.replace("\\", "\\\\").replace("\"", "\\\"");
  }
}
