-- MasterCompiler demo: a small item table
CREATE OR REPLACE TABLE MCDITEM (
  ITEM_ID CHAR(5)       NOT NULL PRIMARY KEY,
  NAME    VARCHAR(30)   NOT NULL,
  PRICE   DECIMAL(9, 2) NOT NULL
);

INSERT INTO MCDITEM VALUES ('A0001', 'Coffee', 4.50), ('A0002', 'Tea', 3.25);
